context("UFO vector subscripting")

test_ufo_subscript <- function (n, subscript, ufo_constructor, named=FALSE, index_type=as.integer) {
  ufo <- ufo_constructor(n)
  data <- index_type(1:n)
  if (named) {
      ufo <- setNames(ufo, as.character(1:n))
      data <- setNames(data, as.character(1:n))
  }
  result <- ufovectors::ufo_subscript(ufo, subscript)
  expected <- data[subscript]
  if (named) {
      # subscripting does not return names, so remove those from expected
      expected <- setNames(expected, NULL)
  }
  expect_equal(result, expected)
}

test_that("ufo integer subscript: null",                         {test_ufo_subscript(n=100000, NULL,                                                                ufo_integer         )})

test_that("ufo integer subscript: logical(0)",                   {test_ufo_subscript(n=100000, logical(0),                                                          ufo_integer         )})
test_that("ufo integer subscript: F",                            {test_ufo_subscript(n=100000, c(T),                                                                ufo_integer         )})
test_that("ufo integer subscript: T",                            {test_ufo_subscript(n=100000, c(F),                                                                ufo_integer         )})
test_that("ufo integer subscript: logical(NA)",                  {test_ufo_subscript(n=100000, as.logical(NA),                                                      ufo_integer         )})
test_that("ufo integer subscript: F,F",                          {test_ufo_subscript(n=100000, c(F, F),                                                             ufo_integer         )})
test_that("ufo integer subscript: F,T",                          {test_ufo_subscript(n=100000, c(F, T),                                                             ufo_integer         )})
test_that("ufo integer subscript: T,F",                          {test_ufo_subscript(n=100000, c(T, F),                                                             ufo_integer         )})
test_that("ufo integer subscript: T,T",                          {test_ufo_subscript(n=100000, c(T, T),                                                             ufo_integer         )})
test_that("ufo integer subscript: F,NA",                         {test_ufo_subscript(n=100000, c(F, NA),                                                            ufo_integer         )})
test_that("ufo integer subscript: NA,F",                         {test_ufo_subscript(n=100000, c(NA, F),                                                            ufo_integer         )})
test_that("ufo integer subscript: NA,T",                         {test_ufo_subscript(n=100000, c(NA, T),                                                            ufo_integer         )})
test_that("ufo integer subscript: T,NA",                         {test_ufo_subscript(n=100000, c(T, NA),                                                            ufo_integer         )})
test_that("ufo integer subscript: F,F,F",                        {test_ufo_subscript(n=100000, c(F, F, F),                                                          ufo_integer         )})
test_that("ufo integer subscript: F,F,T",                        {test_ufo_subscript(n=100000, c(F, F, T),                                                          ufo_integer         )})
test_that("ufo integer subscript: F,T,F",                        {test_ufo_subscript(n=100000, c(F, T, F),                                                          ufo_integer         )})
test_that("ufo integer subscript: F,T,T",                        {test_ufo_subscript(n=100000, c(F, T, T),                                                          ufo_integer         )})
test_that("ufo integer subscript: T,F,F",                        {test_ufo_subscript(n=100000, c(T, F, F),                                                          ufo_integer         )})
test_that("ufo integer subscript: T,F,T",                        {test_ufo_subscript(n=100000, c(T, F, T),                                                          ufo_integer         )})
test_that("ufo integer subscript: T,T,F",                        {test_ufo_subscript(n=100000, c(T, T, F),                                                          ufo_integer         )})
test_that("ufo integer subscript: T,T,T",                        {test_ufo_subscript(n=100000, c(T, T, T),                                                          ufo_integer         )})
test_that("ufo integer subscript: F,F,NA",                       {test_ufo_subscript(n=100000, c(F, F, NA),                                                         ufo_integer         )})
test_that("ufo integer subscript: F,NA,F",                       {test_ufo_subscript(n=100000, c(F, NA, F),                                                         ufo_integer         )})
test_that("ufo integer subscript: F,NA,NA",                      {test_ufo_subscript(n=100000, c(F, NA, NA),                                                        ufo_integer         )})
test_that("ufo integer subscript: NA,F,F",                       {test_ufo_subscript(n=100000, c(NA, F, F),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,F,NA",                      {test_ufo_subscript(n=100000, c(NA, F, NA),                                                        ufo_integer         )})
test_that("ufo integer subscript: NA,NA,F",                      {test_ufo_subscript(n=100000, c(NA, NA, F),                                                        ufo_integer         )})
test_that("ufo integer subscript: F,F,T",                        {test_ufo_subscript(n=100000, c(F, F, T),                                                          ufo_integer         )})
test_that("ufo integer subscript: F,NA,T",                       {test_ufo_subscript(n=100000, c(F, NA, T),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,F,T",                       {test_ufo_subscript(n=100000, c(NA, F, T),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,NA,T",                      {test_ufo_subscript(n=100000, c(NA, NA, T),                                                        ufo_integer         )})
test_that("ufo integer subscript: F,T,NA",                       {test_ufo_subscript(n=100000, c(F, T, NA),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,T,F",                       {test_ufo_subscript(n=100000, c(NA, T, F),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,T,NA",                      {test_ufo_subscript(n=100000, c(NA, T, NA),                                                        ufo_integer         )})
test_that("ufo integer subscript: F,NA,T",                       {test_ufo_subscript(n=100000, c(F, NA, T),                                                         ufo_integer         )})
test_that("ufo integer subscript: NA,T,T",                       {test_ufo_subscript(n=100000, c(NA, T, T),                                                         ufo_integer         )})
test_that("ufo integer subscript: T,F,NA",                       {test_ufo_subscript(n=100000, c(T, F, NA),                                                         ufo_integer         )})
test_that("ufo integer subscript: T,NA,F",                       {test_ufo_subscript(n=100000, c(T, NA, F),                                                         ufo_integer         )})
test_that("ufo integer subscript: T,NA,NA",                      {test_ufo_subscript(n=100000, c(T, NA, NA),                                                        ufo_integer         )})
test_that("ufo integer subscript: T,NA,T",                       {test_ufo_subscript(n=100000, c(T, NA, T),                                                         ufo_integer         )})
test_that("ufo integer subscript: T,T,NA",                       {test_ufo_subscript(n=100000, c(T, T, NA),                                                         ufo_integer         )})
test_that("ufo integer subscript: T,NA,NA",                      {test_ufo_subscript(n=100000, c(T, NA, NA),                                                        ufo_integer         )})
test_that("ufo integer subscript: T..",                          {test_ufo_subscript(n=100000, rep(T, 100000),                                                      ufo_integer         )})
test_that("ufo integer subscript: F..",                          {test_ufo_subscript(n=100000, rep(F, 100000),                                                      ufo_integer         )})
test_that("ufo integer subscript: T,F..",                        {test_ufo_subscript(n=100000, rep(c(T,F), 100000),                                                 ufo_integer         )})
test_that("ufo integer subscript: F,T..",                        {test_ufo_subscript(n=100000, rep(c(F,T), 100000),                                                 ufo_integer         )})

test_that("ufo integer subscript: int integer(0)",               {test_ufo_subscript(n=100000, integer(0),                                                          ufo_integer         )})
test_that("ufo integer subscript: int 0",                        {test_ufo_subscript(n=100000, as.integer(0),                                                       ufo_integer         )})
test_that("ufo integer subscript: int 1",                        {test_ufo_subscript(n=100000, as.integer(1),                                                       ufo_integer         )})
test_that("ufo integer subscript: int 10",                       {test_ufo_subscript(n=100000, as.integer(10),                                                      ufo_integer         )})
test_that("ufo integer subscript: int 42",                       {test_ufo_subscript(n=100000, as.integer(42),                                                      ufo_integer         )})
test_that("ufo integer subscript: int 0,0",                      {test_ufo_subscript(n=100000, as.integer(c(0, 0)),                                                 ufo_integer         )})
test_that("ufo integer subscript: int 0,1,0,N",                  {test_ufo_subscript(n=100000, as.integer(c(1, 0, 1, 100000)),                                      ufo_integer         )})
test_that("ufo integer subscript: int 1,10,100,1000,100",        {test_ufo_subscript(n=100000, as.integer(c(1, 10, 100, 1000, 100)),                                ufo_integer         )})
test_that("ufo integer subscript: int -1",                       {test_ufo_subscript(n=100000, as.integer(-1),                                                      ufo_integer         )})
test_that("ufo integer subscript: int -10",                      {test_ufo_subscript(n=100000, as.integer(-10),                                                     ufo_integer         )})
test_that("ufo integer subscript: int -42",                      {test_ufo_subscript(n=100000, as.integer(-42),                                                     ufo_integer         )})
test_that("ufo integer subscript: int -1,-10,-100,-1000,-100",   {test_ufo_subscript(n=100000, as.integer(-c(1, 10, 100, 1000, 100)),                               ufo_integer         )})
test_that("ufo integer subscript: int few",                      {test_ufo_subscript(n=100000, as.integer(c(4, 10, 7, 100)),                                        ufo_integer         )})
test_that("ufo integer subscript: int many",                     {test_ufo_subscript(n=100000, as.integer(c(1:1000, 2000:5000, 10:1000, 6000:10000)),               ufo_integer         )})
test_that("ufo integer subscript: int all",                      {test_ufo_subscript(n=100000, as.integer(1:100000),                                                ufo_integer         )})
test_that("ufo integer subscript: int few with NAs",             {test_ufo_subscript(n=100000, as.integer(c(4, 10, NA, 7, NA, 100, NA)),                            ufo_integer         )})
test_that("ufo integer subscript: int many with NAs",            {test_ufo_subscript(n=100000, as.integer(c(1:1000, NA, 2000:5000, NA, 10:1000, NA, 6000:10000)),   ufo_integer         )})
test_that("ufo integer subscript: int all with NAs",             {test_ufo_subscript(n=100000, as.integer(c(1:100000, NA)),                                         ufo_integer         )})
test_that("ufo integer subscript: int few negative",             {test_ufo_subscript(n=100000, as.integer(-c(4, 10, 7, 100)),                                       ufo_integer         )})
test_that("ufo integer subscript: int many negative",            {test_ufo_subscript(n=100000, as.integer(-c(1:1000, 2000:5000, 10:1000, 6000:10000)),              ufo_integer         )})
test_that("ufo integer subscript: int all negative",             {test_ufo_subscript(n=100000, as.integer(-(1:100000)),                                             ufo_integer         )})

test_that("ufo integer subscript: num integer(0)",               {test_ufo_subscript(n=100000, numeric(0),                                                          ufo_integer         )})
test_that("ufo integer subscript: num 0",                        {test_ufo_subscript(n=100000, as.numeric(0),                                                       ufo_integer         )})
test_that("ufo integer subscript: num 1",                        {test_ufo_subscript(n=100000, as.numeric(1),                                                       ufo_integer         )})
test_that("ufo integer subscript: num 10",                       {test_ufo_subscript(n=100000, as.numeric(10),                                                      ufo_integer         )})
test_that("ufo integer subscript: num 42",                       {test_ufo_subscript(n=100000, as.numeric(42),                                                      ufo_integer         )})
test_that("ufo integer subscript: num 0,0",                      {test_ufo_subscript(n=100000, as.numeric(c(0, 0)),                                                 ufo_integer         )})
test_that("ufo integer subscript: num 0,1,0,N",                  {test_ufo_subscript(n=100000, as.numeric(c(1, 0, 1, 100000)),                                      ufo_integer         )})
test_that("ufo integer subscript: num 1,10,100,1000,100",        {test_ufo_subscript(n=100000, as.numeric(c(1, 10, 100, 1000, 100)),                                ufo_integer         )})
test_that("ufo integer subscript: num -1",                       {test_ufo_subscript(n=100000, as.numeric(-1),                                                      ufo_integer         )})
test_that("ufo integer subscript: num -10",                      {test_ufo_subscript(n=100000, as.numeric(-10),                                                     ufo_integer         )})
test_that("ufo integer subscript: num -42",                      {test_ufo_subscript(n=100000, as.numeric(-42),                                                     ufo_integer         )})
test_that("ufo integer subscript: num -1,-10,-100,-1000,-100",   {test_ufo_subscript(n=100000, as.numeric(-c(1, 10, 100, 1000, 100)),                               ufo_integer         )})
test_that("ufo integer subscript: num few",                      {test_ufo_subscript(n=100000, as.numeric(c(4, 10, 7, 100)),                                        ufo_integer         )})
test_that("ufo integer subscript: num many",                     {test_ufo_subscript(n=100000, as.numeric(c(1:1000, 2000:5000, 10:1000, 6000:10000)),               ufo_integer         )})
test_that("ufo integer subscript: num all",                      {test_ufo_subscript(n=100000, as.numeric(1:100000),                                                ufo_integer         )})
test_that("ufo integer subscript: num few with NAs",             {test_ufo_subscript(n=100000, as.numeric(c(4, 10, NA, 7, NA, 100, NA)),                            ufo_integer         )})
test_that("ufo integer subscript: num many with NAs",            {test_ufo_subscript(n=100000, as.numeric(c(1:1000, NA, 2000:5000, NA, 10:1000, NA, 6000:10000)),   ufo_integer         )})
test_that("ufo integer subscript: num all with NAs",             {test_ufo_subscript(n=100000, as.numeric(c(1:100000, NA)),                                         ufo_integer         )})
test_that("ufo integer subscript: num few negative",             {test_ufo_subscript(n=100000, as.numeric(-c(4, 10, 7, 100)),                                       ufo_integer         )})
test_that("ufo integer subscript: num many negative",            {test_ufo_subscript(n=100000, as.numeric(-c(1:1000, 2000:5000, 10:1000, 6000:10000)),              ufo_integer         )})
test_that("ufo integer subscript: num all negative",             {test_ufo_subscript(n=100000, as.numeric(-(1:100000)),                                             ufo_integer         )})
test_that("ufo integer subscript: num 0.1",                      {test_ufo_subscript(n=100000, as.numeric(0.1),                                                     ufo_integer         )})
test_that("ufo integer subscript: num 1.1",                      {test_ufo_subscript(n=100000, as.numeric(1.1),                                                     ufo_integer         )})
test_that("ufo integer subscript: num 10.5",                     {test_ufo_subscript(n=100000, as.numeric(10.5),                                                    ufo_integer         )})
test_that("ufo integer subscript: num 42.9",                     {test_ufo_subscript(n=100000, as.numeric(42.9),                                                    ufo_integer         )})
test_that("ufo integer subscript: num -0.1",                     {test_ufo_subscript(n=100000, as.numeric(-0.1),                                                    ufo_integer         )})
test_that("ufo integer subscript: num -1.1",                     {test_ufo_subscript(n=100000, as.numeric(-1.1),                                                    ufo_integer         )})
test_that("ufo integer subscript: num -10.5",                    {test_ufo_subscript(n=100000, as.numeric(-10.5),                                                   ufo_integer         )})
test_that("ufo integer subscript: num -42.9",                    {test_ufo_subscript(n=100000, as.numeric(-42.9),                                                   ufo_integer         )})

test_that("ufo integer subscript: str character(0)",             {test_ufo_subscript(n=100000, character(0),                                                        ufo_integer         )})
test_that("ufo integer subscript: str 0",                        {test_ufo_subscript(n=100000, as.character(0),                                                     ufo_integer         )})
test_that("ufo integer subscript: str 1",                        {test_ufo_subscript(n=100000, as.character(1),                                                     ufo_integer         )})
test_that("ufo integer subscript: str 10",                       {test_ufo_subscript(n=100000, as.character(10),                                                    ufo_integer         )})
test_that("ufo integer subscript: str 42",                       {test_ufo_subscript(n=100000, as.character(42),                                                    ufo_integer         )})
test_that("ufo integer subscript: str 0,0",                      {test_ufo_subscript(n=100000, as.character(c(0, 0)),                                               ufo_integer         )})
test_that("ufo integer subscript: str 0,1,0,N",                  {test_ufo_subscript(n=100000, as.character(c(1, 0, 1, 100000)),                                    ufo_integer         )})
test_that("ufo integer subscript: str 1,10,100,1000,100",        {test_ufo_subscript(n=100000, as.character(c(1, 10, 100, 1000, 100)),                              ufo_integer         )})
test_that("ufo integer subscript: str few",                      {test_ufo_subscript(n=100000, as.character(c(4, 10, 7, 100)),                                      ufo_integer         )})
test_that("ufo integer subscript: str many",                     {test_ufo_subscript(n=100000, as.character(c(1:1000, 2000:5000, 10:1000, 6000:10000)),             ufo_integer         )})
test_that("ufo integer subscript: str all",                      {test_ufo_subscript(n=100000, as.character(1:100000),                                              ufo_integer         )})
test_that("ufo integer subscript: str few with NAs",             {test_ufo_subscript(n=100000, as.character(c(4, 10, NA, 7, NA, 100, NA)),                          ufo_integer         )})
test_that("ufo integer subscript: str many with NAs",            {test_ufo_subscript(n=100000, as.character(c(1:1000, NA, 2000:5000, NA, 10:1000, NA, 6000:10000)), ufo_integer         )})
test_that("ufo integer subscript: str all with NAs",             {test_ufo_subscript(n=100000, as.character(c(1:100000, NA)),                                       ufo_integer         )})

test_that("ufo integer +names subscript: str character(0)",      {test_ufo_subscript(n=100000, character(0),                                                        ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 0",                 {test_ufo_subscript(n=100000, as.character(0),                                                     ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 1",                 {test_ufo_subscript(n=100000, as.character(1),                                                     ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 10",                {test_ufo_subscript(n=100000, as.character(10),                                                    ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 42",                {test_ufo_subscript(n=100000, as.character(42),                                                    ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 0,0",               {test_ufo_subscript(n=100000, as.character(c(0, 0)),                                               ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 0,1,0,N",           {test_ufo_subscript(n=100000, as.character(c(1, 0, 1, 100000)),                                    ufo_integer, named=T)})
test_that("ufo integer +names subscript: str 1,10,100,1000,100", {test_ufo_subscript(n=100000, as.character(c(1, 10, 100, 1000, 100)),                              ufo_integer, named=T)})
test_that("ufo integer +names subscript: str few",               {test_ufo_subscript(n=100000, as.character(c(4, 10, 7, 100)),                                      ufo_integer, named=T)})
test_that("ufo integer +names subscript: str many",              {test_ufo_subscript(n=100000, as.character(c(1:1000, 2000:5000, 10:1000, 6000:10000)),             ufo_integer, named=T)})
test_that("ufo integer +names subscript: str all",               {test_ufo_subscript(n=100000, as.character(1:100000),                                              ufo_integer, named=T)})
test_that("ufo integer +names subscript: str few with NAs",      {test_ufo_subscript(n=100000, as.character(c(4, 10, NA, 7, NA, 100, NA)),                          ufo_integer, named=T)})
test_that("ufo integer +names subscript: str many with NAs",     {test_ufo_subscript(n=100000, as.character(c(1:1000, NA, 2000:5000, NA, 10:1000, NA, 6000:10000)), ufo_integer, named=T)})
test_that("ufo integer +names subscript: str all with NAs",      {test_ufo_subscript(n=100000, as.character(c(1:100000, NA)),                                       ufo_integer, named=T)})

test_that("ufo numeric subscript: null",                         {test_ufo_subscript(n=100000, NULL,                                                                ufo_numeric         )})
# TODO

test_that("ufo logical subscript: null",                         {test_ufo_subscript(n=100000, NULL,                                                                ufo_logical         )})
# TODO

test_that("ufo complex subscript: null",                         {test_ufo_subscript(n=100000, NULL,                                                                ufo_complex         )})
# TODO

test_that("ufo raw subscript: null",                             {test_ufo_subscript(n=100000, NULL,                                                                ufo_raw             )})
# TODO

test_that("ufo character subscript: null",                       {test_ufo_subscript(n=100000, NULL,                                                                ufo_character       )})
# TODO
