context("UFO vector assignment")

test_ufo_assign <- function (data, subscript, ufo_constructor) {
  new_data_length <- length(data[subscript])
  set.seed(42)
  new_data <- sample(data, new_data_length, replace=TRUE)

  ufo <- ufo_constructor(length(data))
  #ufo[seq_len(length(data))] <- data

  ufo[subscript] <- new_data
  #ufo[ufo_subscript(ufo, subscript)] <- new_data

  reference_vector <- vector(typeof(ufo), length(data))
  reference_vector[subscript] <- new_data

  expect_equal(ufo, reference_vector)
  expect_equal(is_ufo(ufo), TRUE)
}

test_that("ufo integer assign: NULL",           {test_ufo_assign(data=as.integer(1:100000), subscript=NULL,               ufo_integer)})
test_that("ufo numeric assign: NULL",           {test_ufo_assign(data=as.numeric(1:100000), subscript=NULL,               ufo_numeric)})
test_that("ufo raw     assign: NULL",           {test_ufo_assign(data=as.raw(1:100000),     subscript=NULL,               ufo_raw)})
test_that("ufo logical assign: NULL",           {test_ufo_assign(data=as.logical(1:100000), subscript=NULL,               ufo_logical)})
test_that("ufo complex assign: NULL",           {test_ufo_assign(data=as.complex(1:100000), subscript=NULL,               ufo_complex)})
test_that("ufo integer assign: num 0",          {test_ufo_assign(data=as.integer(1:100000), subscript=0,                  ufo_integer)})
test_that("ufo integer assign: num 1",          {test_ufo_assign(data=as.integer(1:100000), subscript=1,                  ufo_integer)})
test_that("ufo integer assign: num N/2",        {test_ufo_assign(data=as.integer(1:100000), subscript=50000,              ufo_integer)})
test_that("ufo integer assign: num N",          {test_ufo_assign(data=as.integer(1:100000), subscript=100000,             ufo_integer)})
test_that("ufo integer assign: num 1:10",       {test_ufo_assign(data=as.integer(1:100000), subscript=1:10,               ufo_integer)})
test_that("ufo integer assign: num 1:1000",     {test_ufo_assign(data=as.integer(1:100000), subscript=1:1000,             ufo_integer)})
test_that("ufo integer assign: num 1:N",        {test_ufo_assign(data=as.integer(1:100000), subscript=1:100000,           ufo_integer)})
test_that("ufo integer assign: num N/2:N",      {test_ufo_assign(data=as.integer(1:100000), subscript=50000:100000,       ufo_integer)})
test_that("ufo integer assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.integer(1:100000), subscript=2*(1:50000),        ufo_integer)})
test_that("ufo integer assign: num -1",         {test_ufo_assign(data=as.integer(1:100000), subscript=-1,                 ufo_integer)})
test_that("ufo integer assign: num -(N/2)",     {test_ufo_assign(data=as.integer(1:100000), subscript=-50000,             ufo_integer)})
test_that("ufo integer assign: num -N",         {test_ufo_assign(data=as.integer(1:100000), subscript=-100000,            ufo_integer)})
test_that("ufo integer assign: num -(1:10)",    {test_ufo_assign(data=as.integer(1:100000), subscript=-(1:10),            ufo_integer)})
test_that("ufo integer assign: num -(1:1000)",  {test_ufo_assign(data=as.integer(1:100000), subscript=-(1:1000),          ufo_integer)})
test_that("ufo integer assign: num -(1:N)",     {test_ufo_assign(data=as.integer(1:100000), subscript=-(1:100000),        ufo_integer)})
test_that("ufo integer assign: num -(N/2:N)",   {test_ufo_assign(data=as.integer(1:100000), subscript=-(50000:100000),    ufo_integer)})
test_that("ufo integer assign: num -2*(2:N/2)", {test_ufo_assign(data=as.integer(1:100000), subscript=-2*(1:50000),       ufo_integer)})
test_that("ufo numeric assign: num 0",          {test_ufo_assign(data=as.numeric(1:100000), subscript=0,                  ufo_numeric)})
test_that("ufo numeric assign: num 1",          {test_ufo_assign(data=as.numeric(1:100000), subscript=1,                  ufo_numeric)})
test_that("ufo numeric assign: num N/2",        {test_ufo_assign(data=as.numeric(1:100000), subscript=50000,              ufo_numeric)})
test_that("ufo numeric assign: num N",          {test_ufo_assign(data=as.numeric(1:100000), subscript=100000,             ufo_numeric)})
test_that("ufo numeric assign: num 1:10",       {test_ufo_assign(data=as.numeric(1:100000), subscript=1:10,               ufo_numeric)})
test_that("ufo numeric assign: num 1:1000",     {test_ufo_assign(data=as.numeric(1:100000), subscript=1:1000,             ufo_numeric)})
test_that("ufo numeric assign: num 1:N",        {test_ufo_assign(data=as.numeric(1:100000), subscript=1:100000,           ufo_numeric)})
test_that("ufo numeric assign: num N/2:N",      {test_ufo_assign(data=as.numeric(1:100000), subscript=50000:100000,       ufo_numeric)})
test_that("ufo numeric assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.numeric(1:100000), subscript=2*(1:50000),        ufo_numeric)})
test_that("ufo numeric assign: num -1",         {test_ufo_assign(data=as.numeric(1:100000), subscript=-1,                 ufo_numeric)})
test_that("ufo numeric assign: num -(N/2)",     {test_ufo_assign(data=as.numeric(1:100000), subscript=-50000,             ufo_numeric)})
test_that("ufo numeric assign: num -N",         {test_ufo_assign(data=as.numeric(1:100000), subscript=-100000,            ufo_numeric)})
test_that("ufo numeric assign: num -(1:10)",    {test_ufo_assign(data=as.numeric(1:100000), subscript=-(1:10),            ufo_numeric)})
test_that("ufo numeric assign: num -(1:1000)",  {test_ufo_assign(data=as.numeric(1:100000), subscript=-(1:1000),          ufo_numeric)})
test_that("ufo numeric assign: num -(1:N)",     {test_ufo_assign(data=as.numeric(1:100000), subscript=-(1:100000),        ufo_numeric)})
test_that("ufo numeric assign: num -(N/2:N)",   {test_ufo_assign(data=as.numeric(1:100000), subscript=-(50000:100000),    ufo_numeric)})
test_that("ufo numeric assign: num -2*(2:N/2)", {test_ufo_assign(data=as.numeric(1:100000), subscript=-2*(1:50000),       ufo_numeric)})
test_that("ufo complex assign: num 0",          {test_ufo_assign(data=as.complex(1:100000), subscript=0,                  ufo_complex)})
test_that("ufo complex assign: num 1",          {test_ufo_assign(data=as.complex(1:100000), subscript=1,                  ufo_complex)})
test_that("ufo complex assign: num N/2",        {test_ufo_assign(data=as.complex(1:100000), subscript=50000,              ufo_complex)})
test_that("ufo complex assign: num N",          {test_ufo_assign(data=as.complex(1:100000), subscript=100000,             ufo_complex)})
test_that("ufo complex assign: num 1:10",       {test_ufo_assign(data=as.complex(1:100000), subscript=1:10,               ufo_complex)})
test_that("ufo complex assign: num 1:1000",     {test_ufo_assign(data=as.complex(1:100000), subscript=1:1000,             ufo_complex)})
test_that("ufo complex assign: num 1:N",        {test_ufo_assign(data=as.complex(1:100000), subscript=1:100000,           ufo_complex)})
test_that("ufo complex assign: num N/2:N",      {test_ufo_assign(data=as.complex(1:100000), subscript=50000:100000,       ufo_complex)})
test_that("ufo complex assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.complex(1:100000), subscript=2*(1:50000),        ufo_complex)})
test_that("ufo complex assign: num -1",         {test_ufo_assign(data=as.complex(1:100000), subscript=-1,                 ufo_complex)})
test_that("ufo complex assign: num -(N/2)",     {test_ufo_assign(data=as.complex(1:100000), subscript=-50000,             ufo_complex)})
test_that("ufo complex assign: num -N",         {test_ufo_assign(data=as.complex(1:100000), subscript=-100000,            ufo_complex)})
test_that("ufo complex assign: num -(1:10)",    {test_ufo_assign(data=as.complex(1:100000), subscript=-(1:10),            ufo_complex)})
test_that("ufo complex assign: num -(1:1000)",  {test_ufo_assign(data=as.complex(1:100000), subscript=-(1:1000),          ufo_complex)})
test_that("ufo complex assign: num -(1:N)",     {test_ufo_assign(data=as.complex(1:100000), subscript=-(1:100000),        ufo_complex)})
test_that("ufo complex assign: num -(N/2:N)",   {test_ufo_assign(data=as.complex(1:100000), subscript=-(50000:100000),    ufo_complex)})
test_that("ufo complex assign: num -2*(2:N/2)", {test_ufo_assign(data=as.complex(1:100000), subscript=-2*(1:50000),       ufo_complex)})
test_that("ufo raw     assign: num 0",          {test_ufo_assign(data=as.raw(1:100000),     subscript=0,                  ufo_raw)})
test_that("ufo raw     assign: num 1",          {test_ufo_assign(data=as.raw(1:100000),     subscript=1,                  ufo_raw)})
test_that("ufo raw     assign: num N/2",        {test_ufo_assign(data=as.raw(1:100000),     subscript=50000,              ufo_raw)})
test_that("ufo raw     assign: num N",          {test_ufo_assign(data=as.raw(1:100000),     subscript=100000,             ufo_raw)})
test_that("ufo raw     assign: num 1:10",       {test_ufo_assign(data=as.raw(1:100000),     subscript=1:10,               ufo_raw)})
test_that("ufo raw     assign: num 1:1000",     {test_ufo_assign(data=as.raw(1:100000),     subscript=1:1000,             ufo_raw)})
test_that("ufo raw     assign: num 1:N",        {test_ufo_assign(data=as.raw(1:100000),     subscript=1:100000,           ufo_raw)})
test_that("ufo raw     assign: num N/2:N",      {test_ufo_assign(data=as.raw(1:100000),     subscript=50000:100000,       ufo_raw)})
test_that("ufo raw     assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.raw(1:100000),     subscript=2*(1:50000),        ufo_raw)})
test_that("ufo raw     assign: num -1",         {test_ufo_assign(data=as.raw(1:100000),     subscript=-1,                 ufo_raw)})
test_that("ufo raw     assign: num -(N/2)",     {test_ufo_assign(data=as.raw(1:100000),     subscript=-50000,             ufo_raw)})
test_that("ufo raw     assign: num -N",         {test_ufo_assign(data=as.raw(1:100000),     subscript=-100000,            ufo_raw)})
test_that("ufo raw     assign: num -(1:10)",    {test_ufo_assign(data=as.raw(1:100000),     subscript=-(1:10),            ufo_raw)})
test_that("ufo raw     assign: num -(1:1000)",  {test_ufo_assign(data=as.raw(1:100000),     subscript=-(1:1000),          ufo_raw)})
test_that("ufo raw     assign: num -(1:N)",     {test_ufo_assign(data=as.raw(1:100000),     subscript=-(1:100000),        ufo_raw)})
test_that("ufo raw     assign: num -(N/2:N)",   {test_ufo_assign(data=as.raw(1:100000),     subscript=-(50000:100000),    ufo_raw)})
test_that("ufo raw     assign: num -2*(2:N/2)", {test_ufo_assign(data=as.raw(1:100000),     subscript=-2*(1:50000),       ufo_raw)})
test_that("ufo logical assign: num 0",          {test_ufo_assign(data=as.logical(1:100000), subscript=0,                  ufo_logical)})
test_that("ufo logical assign: num 1",          {test_ufo_assign(data=as.logical(1:100000), subscript=1,                  ufo_logical)})
test_that("ufo logical assign: num N/2",        {test_ufo_assign(data=as.logical(1:100000), subscript=50000,              ufo_logical)})
test_that("ufo logical assign: num N",          {test_ufo_assign(data=as.logical(1:100000), subscript=100000,             ufo_logical)})
test_that("ufo logical assign: num 1:10",       {test_ufo_assign(data=as.logical(1:100000), subscript=1:10,               ufo_logical)})
test_that("ufo logical assign: num 1:1000",     {test_ufo_assign(data=as.logical(1:100000), subscript=1:1000,             ufo_logical)})
test_that("ufo logical assign: num 1:N",        {test_ufo_assign(data=as.logical(1:100000), subscript=1:100000,           ufo_logical)})
test_that("ufo logical assign: num N/2:N",      {test_ufo_assign(data=as.logical(1:100000), subscript=50000:100000,       ufo_logical)})
test_that("ufo logical assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.logical(1:100000), subscript=2*(1:50000),        ufo_logical)})
test_that("ufo logical assign: num -1",         {test_ufo_assign(data=as.logical(1:100000), subscript=-1,                 ufo_logical)})
test_that("ufo logical assign: num -(N/2)",     {test_ufo_assign(data=as.logical(1:100000), subscript=-50000,             ufo_logical)})
test_that("ufo logical assign: num -N",         {test_ufo_assign(data=as.logical(1:100000), subscript=-100000,            ufo_logical)})
test_that("ufo logical assign: num -(1:10)",    {test_ufo_assign(data=as.logical(1:100000), subscript=-(1:10),            ufo_logical)})
test_that("ufo logical assign: num -(1:1000)",  {test_ufo_assign(data=as.logical(1:100000), subscript=-(1:1000),          ufo_logical)})
test_that("ufo logical assign: num -(1:N)",     {test_ufo_assign(data=as.logical(1:100000), subscript=-(1:100000),        ufo_logical)})
test_that("ufo logical assign: num -(N/2:N)",   {test_ufo_assign(data=as.logical(1:100000), subscript=-(50000:100000),    ufo_logical)})
test_that("ufo logical assign: num -2*(2:N/2)", {test_ufo_assign(data=as.logical(1:100000), subscript=-2*(1:50000),       ufo_logical)})
test_that("ufo string  assign: num 0",          {test_ufo_assign(data=as.character(1:100000), subscript=0,                ufo_character)})
test_that("ufo string  assign: num 1",          {test_ufo_assign(data=as.character(1:100000), subscript=1,                ufo_character)})
test_that("ufo string  assign: num N/2",        {test_ufo_assign(data=as.character(1:100000), subscript=50000,            ufo_character)})
test_that("ufo string  assign: num N",          {test_ufo_assign(data=as.character(1:100000), subscript=100000,           ufo_character)})
test_that("ufo string  assign: num 1:10",       {test_ufo_assign(data=as.character(1:100000), subscript=1:10,             ufo_character)})
test_that("ufo string  assign: num 1:1000",     {test_ufo_assign(data=as.character(1:100000), subscript=1:1000,           ufo_character)})
test_that("ufo string  assign: num 1:N",        {test_ufo_assign(data=as.character(1:100000), subscript=1:100000,         ufo_character)})
test_that("ufo string  assign: num N/2:N",      {test_ufo_assign(data=as.character(1:100000), subscript=50000:100000,     ufo_character)})
test_that("ufo string  assign: num 2*(2:N/2)",  {test_ufo_assign(data=as.character(1:100000), subscript=2*(1:50000),      ufo_character)})
test_that("ufo string  assign: num -1",         {test_ufo_assign(data=as.character(1:100000), subscript=-1,               ufo_character)})
test_that("ufo string  assign: num -(N/2)",     {test_ufo_assign(data=as.character(1:100000), subscript=-50000,           ufo_character)})
test_that("ufo string  assign: num -N",         {test_ufo_assign(data=as.character(1:100000), subscript=-100000,          ufo_character)})
test_that("ufo string  assign: num -(1:10)",    {test_ufo_assign(data=as.character(1:100000), subscript=-(1:10),          ufo_character)})
test_that("ufo string  assign: num -(1:1000)",  {test_ufo_assign(data=as.character(1:100000), subscript=-(1:1000),        ufo_character)})
test_that("ufo string  assign: num -(1:N)",     {test_ufo_assign(data=as.character(1:100000), subscript=-(1:100000),      ufo_character)})
test_that("ufo string  assign: num -(N/2:N)",   {test_ufo_assign(data=as.character(1:100000), subscript=-(50000:100000),  ufo_character)})
test_that("ufo string  assign: num -2*(2:N/2)", {test_ufo_assign(data=as.character(1:100000), subscript=-2*(1:50000),     ufo_character)})
test_that("ufo integer assign: int 0",          {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(0),                  ufo_integer)})
test_that("ufo integer assign: int 1",          {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(1),                  ufo_integer)})
test_that("ufo integer assign: int N/2",        {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(50000),              ufo_integer)})
test_that("ufo integer assign: int N",          {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(100000),             ufo_integer)})
test_that("ufo integer assign: int 1:10",       {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(1:10),               ufo_integer)})
test_that("ufo integer assign: int 1:1000",     {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(1:1000),             ufo_integer)})
test_that("ufo integer assign: int 1:N",        {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(1:100000),           ufo_integer)})
test_that("ufo integer assign: int N/2:N",      {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(50000:100000),       ufo_integer)})
test_that("ufo integer assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(2*(1:50000)),        ufo_integer)})
test_that("ufo integer assign: int -1",         {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-1),                 ufo_integer)})
test_that("ufo integer assign: int -(N/2)",     {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-50000),             ufo_integer)})
test_that("ufo integer assign: int -N",         {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-100000),            ufo_integer)})
test_that("ufo integer assign: int -(1:10)",    {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-(1:10)),            ufo_integer)})
test_that("ufo integer assign: int -(1:1000)",  {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-(1:1000)),          ufo_integer)})
test_that("ufo integer assign: int -(1:N)",     {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-(1:100000)),        ufo_integer)})
test_that("ufo integer assign: int -(N/2:N)",   {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-(50000:100000)),    ufo_integer)})
test_that("ufo integer assign: int -2*(2:N/2)", {test_ufo_assign(data=as.integer(1:100000), subscript=as.integer(-2*(1:50000)),       ufo_integer)})
test_that("ufo numeric assign: int 0",          {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(0),                  ufo_numeric)})
test_that("ufo numeric assign: int 1",          {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(1),                  ufo_numeric)})
test_that("ufo numeric assign: int N/2",        {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(50000),              ufo_numeric)})
test_that("ufo numeric assign: int N",          {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(100000),             ufo_numeric)})
test_that("ufo numeric assign: int 1:10",       {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(1:10),               ufo_numeric)})
test_that("ufo numeric assign: int 1:1000",     {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(1:1000),             ufo_numeric)})
test_that("ufo numeric assign: int 1:N",        {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(1:100000),           ufo_numeric)})
test_that("ufo numeric assign: int N/2:N",      {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(50000:100000),       ufo_numeric)})
test_that("ufo numeric assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(2*(1:50000)),        ufo_numeric)})
test_that("ufo numeric assign: int -1",         {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-1),                 ufo_numeric)})
test_that("ufo numeric assign: int -(N/2)",     {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-50000),             ufo_numeric)})
test_that("ufo numeric assign: int -N",         {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-100000),            ufo_numeric)})
test_that("ufo numeric assign: int -(1:10)",    {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-(1:10)),            ufo_numeric)})
test_that("ufo numeric assign: int -(1:1000)",  {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-(1:1000)),          ufo_numeric)})
test_that("ufo numeric assign: int -(1:N)",     {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-(1:100000)),        ufo_numeric)})
test_that("ufo numeric assign: int -(N/2:N)",   {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-(50000:100000)),    ufo_numeric)})
test_that("ufo numeric assign: int -2*(2:N/2)", {test_ufo_assign(data=as.numeric(1:100000), subscript=as.integer(-2*(1:50000)),       ufo_numeric)})
test_that("ufo complex assign: int 0",          {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(0),                  ufo_complex)})
test_that("ufo complex assign: int 1",          {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(1),                  ufo_complex)})
test_that("ufo complex assign: int N/2",        {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(50000),              ufo_complex)})
test_that("ufo complex assign: int N",          {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(100000),             ufo_complex)})
test_that("ufo complex assign: int 1:10",       {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(1:10),               ufo_complex)})
test_that("ufo complex assign: int 1:1000",     {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(1:1000),             ufo_complex)})
test_that("ufo complex assign: int 1:N",        {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(1:100000),           ufo_complex)})
test_that("ufo complex assign: int N/2:N",      {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(50000:100000),       ufo_complex)})
test_that("ufo complex assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(2*(1:50000)),        ufo_complex)})
test_that("ufo complex assign: int -1",         {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-1),                 ufo_complex)})
test_that("ufo complex assign: int -(N/2)",     {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-50000),             ufo_complex)})
test_that("ufo complex assign: int -N",         {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-100000),            ufo_complex)})
test_that("ufo complex assign: int -(1:10)",    {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-(1:10)),            ufo_complex)})
test_that("ufo complex assign: int -(1:1000)",  {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-(1:1000)),          ufo_complex)})
test_that("ufo complex assign: int -(1:N)",     {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-(1:100000)),        ufo_complex)})
test_that("ufo complex assign: int -(N/2:N)",   {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-(50000:100000)),    ufo_complex)})
test_that("ufo complex assign: int -2*(2:N/2)", {test_ufo_assign(data=as.complex(1:100000), subscript=as.integer(-2*(1:50000)),       ufo_complex)})
test_that("ufo raw     assign: int 0",          {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(0),                  ufo_raw)})
test_that("ufo raw     assign: int 1",          {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(1),                  ufo_raw)})
test_that("ufo raw     assign: int N/2",        {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(50000),              ufo_raw)})
test_that("ufo raw     assign: int N",          {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(100000),             ufo_raw)})
test_that("ufo raw     assign: int 1:10",       {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(1:10),               ufo_raw)})
test_that("ufo raw     assign: int 1:1000",     {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(1:1000),             ufo_raw)})
test_that("ufo raw     assign: int 1:N",        {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(1:100000),           ufo_raw)})
test_that("ufo raw     assign: int N/2:N",      {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(50000:100000),       ufo_raw)})
test_that("ufo raw     assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(2*(1:50000)),        ufo_raw)})
test_that("ufo raw     assign: int -1",         {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-1),                 ufo_raw)})
test_that("ufo raw     assign: int -(N/2)",     {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-50000),             ufo_raw)})
test_that("ufo raw     assign: int -N",         {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-100000),            ufo_raw)})
test_that("ufo raw     assign: int -(1:10)",    {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-(1:10)),            ufo_raw)})
test_that("ufo raw     assign: int -(1:1000)",  {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-(1:1000)),          ufo_raw)})
test_that("ufo raw     assign: int -(1:N)",     {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-(1:100000)),        ufo_raw)})
test_that("ufo raw     assign: int -(N/2:N)",   {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-(50000:100000)),    ufo_raw)})
test_that("ufo raw     assign: int -2*(2:N/2)", {test_ufo_assign(data=as.raw(1:100000),     subscript=as.integer(-2*(1:50000)),       ufo_raw)})
test_that("ufo logical assign: int 0",          {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(0),                  ufo_logical)})
test_that("ufo logical assign: int 1",          {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(1),                  ufo_logical)})
test_that("ufo logical assign: int N/2",        {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(50000),              ufo_logical)})
test_that("ufo logical assign: int N",          {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(100000),             ufo_logical)})
test_that("ufo logical assign: int 1:10",       {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(1:10),               ufo_logical)})
test_that("ufo logical assign: int 1:1000",     {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(1:1000),             ufo_logical)})
test_that("ufo logical assign: int 1:N",        {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(1:100000),           ufo_logical)})
test_that("ufo logical assign: int N/2:N",      {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(50000:100000),       ufo_logical)})
test_that("ufo logical assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(2*(1:50000)),        ufo_logical)})
test_that("ufo logical assign: int -1",         {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-1),                 ufo_logical)})
test_that("ufo logical assign: int -(N/2)",     {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-50000),             ufo_logical)})
test_that("ufo logical assign: int -N",         {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-100000),            ufo_logical)})
test_that("ufo logical assign: int -(1:10)",    {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-(1:10)),            ufo_logical)})
test_that("ufo logical assign: int -(1:1000)",  {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-(1:1000)),          ufo_logical)})
test_that("ufo logical assign: int -(1:N)",     {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-(1:100000)),        ufo_logical)})
test_that("ufo logical assign: int -(N/2:N)",   {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-(50000:100000)),    ufo_logical)})
test_that("ufo logical assign: int -2*(2:N/2)", {test_ufo_assign(data=as.logical(1:100000), subscript=as.integer(-2*(1:50000)),       ufo_logical)})
test_that("ufo string  assign: int 0",          {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(0),                ufo_character)})
test_that("ufo string  assign: int 1",          {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(1),                ufo_character)})
test_that("ufo string  assign: int N/2",        {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(50000),            ufo_character)})
test_that("ufo string  assign: int N",          {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(100000),           ufo_character)})
test_that("ufo string  assign: int 1:10",       {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(1:10),             ufo_character)})
test_that("ufo string  assign: int 1:1000",     {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(1:1000),           ufo_character)})
test_that("ufo string  assign: int 1:N",        {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(1:100000),         ufo_character)})
test_that("ufo string  assign: int N/2:N",      {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(50000:100000),     ufo_character)})
test_that("ufo string  assign: int 2*(2:N/2)",  {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(2*(1:50000)),      ufo_character)})
test_that("ufo string  assign: int -1",         {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-1),               ufo_character)})
test_that("ufo string  assign: int -(N/2)",     {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-50000),           ufo_character)})
test_that("ufo string  assign: int -N",         {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-100000),          ufo_character)})
test_that("ufo string  assign: int -(1:10)",    {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-(1:10)),          ufo_character)})
test_that("ufo string  assign: int -(1:1000)",  {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-(1:1000)),        ufo_character)})
test_that("ufo string  assign: int -(1:N)",     {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-(1:100000)),      ufo_character)})
test_that("ufo string  assign: int -(N/2:N)",   {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-(50000:100000)),  ufo_character)})
test_that("ufo string  assign: int -2*(2:N/2)", {test_ufo_assign(data=as.character(1:100000), subscript=as.integer(-2*(1:50000)),     ufo_character)})